#!/usr/bin/env bash
set -e

TAG=v0.4.2

# exit if there is evidence of installation
[ -e ./psc-package.tar.gz ] && exit 0;

# remove stubs
rm -rf ./psc-package

# osx or linux install
if [ "$(uname -s)" == "Darwin" ]
then
  curl --location --output ./psc-package.tar.gz --silent https://github.com/purescript/psc-package/releases/download/$TAG/macos.tar.gz
else
  wget -O ./psc-package.tar.gz https://github.com/purescript/psc-package/releases/download/$TAG/linux64.tar.gz
fi

# unpack
tar -xvf ./psc-package.tar.gz -C ./
